list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/control/control_bar/control_bar_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/control/control_button/control_button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/control/control_group/control_group_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/control/control_music/control_music_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/control/control_panel/control_panel_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/control/control_slider/control_slider_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/control/control_switch/control_switch_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/dialogs/info_dialog/info_dialog_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_bar/hs_bar_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_button_icon/hs_button_icon_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_button_text/hs_button_text_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_button/hs_button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_card/hs_card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_column/hs_column_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_container/hs_container_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_dropdown_item/hs_dropdown_item_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_dropdown/hs_dropdown_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_info_sb_sb/hs_info_sb_sb_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_info_sb/hs_info_sb_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_info/hs_info_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_lap_item/hs_lap_item_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_line/hs_line_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_roller/hs_roller_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_row/hs_row_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_slider/hs_slider_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_space/hs_space_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_switch/hs_switch_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_text_icon/hs_text_icon_normal/hs_text_icon_normal_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_text/hs_tag_normal/hs_tag_normal_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_text/hs_tag_small/hs_tag_small_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_text/hs_text_large/hs_text_large_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_text/hs_text_normal/hs_text_normal_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_text/hs_text_small/hs_text_small_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_title_pill/hs_title_pill_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_title/hs_title_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/items/app_item/app_item_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/items/contact_item/contact_item_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/items/notification_item/notification_item_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/items/panel_dot_item/panel_dot_item_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/music/music_info/music_info_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/music/music_widget/music_widget_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/settings/settings_about/settings_about_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/settings/settings_alert/settings_alert_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/settings/settings_battery/settings_battery_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/settings/settings_display/settings_display_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/settings/settings_storage/settings_storage_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/settings/settings_system/settings_system_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/simple/simple_bar/simple_bar_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/timers/timer_countdown/timer_countdown_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/timers/timer_list/timer_list_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/watchfaces/face_preview/face_preview_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/watchfaces/watchface_default/watchface_default_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/weather/daily_forecast/daily_forecast_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/weather/hourly_forecast/hourly_forecast_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/weather/weather_widget/weather_widget_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_14_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_16_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_18_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_20_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_30_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_40_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_70_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_100_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_140_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_el_14_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_el_16_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_el_18_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_el_20_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_el_30_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_el_40_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_hi_14_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_hi_16_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_hi_18_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_hi_20_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_hi_30_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_hi_40_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_jp_14_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_jp_16_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_jp_18_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_jp_20_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_jp_30_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_jp_40_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_latin_14_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_latin_16_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_latin_18_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_latin_20_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_latin_30_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_latin_40_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_ru_14_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_ru_16_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_ru_18_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_ru_20_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_ru_30_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_ru_40_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_th_14_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_th_16_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_th_18_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_th_20_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_th_30_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_th_40_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_zh_14_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_zh_16_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_zh_18_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_zh_20_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_zh_30_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_zh_40_data.c
  ${CMAKE_CURRENT_LIST_DIR}/helios_ui_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/helios_ui.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_application_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_arrow_up_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_back_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_brightness_empty_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_brightness_full_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_chat_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_connect_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_contacts_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_dnd_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_empty_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_folder_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_gear_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_lap_time_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_list_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_measurement_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_music_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_music_next_32_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_music_pause_32_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_music_play_32_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_music_previous_32_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_mute_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_navigation_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_next_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_calendar_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_chat_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_dingtalk_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_download_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_facebook_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_hangouts_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_instagram_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_kakao_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_line_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_mail_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_messenger_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_paypal_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_qq_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_skype_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_snapchat_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_telegram_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_tiktok_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_twitter_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_viber_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_vk_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_wechat_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_weibo_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_nt_whatsapp_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_phone_link_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_play_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_qr_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_restart_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_running_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_settings_bell_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_settings_brightness_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_settings_harddisk_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_settings_information_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_settings_monitor_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_settings_power_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_settings_rotate_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_settings_smartwatch_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_sleep_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_spotify_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_stop_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_stopwatch_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_timer_cancel_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_timer_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_timer_pause_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_timer_start_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_turn_left_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_user_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_vibration_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_vol_down_32_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_vol_up_32_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_volume_high_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_volume_low_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_weather_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_weather_humidity_icon_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_weather_temp_down_icon_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_weather_temp_up_icon_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_weather_uv_icon_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_wifi_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_wt_cloud_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_wt_haze_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_wt_rain_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_wt_snow_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_wt_sun_cloud_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_wt_sun_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_wt_tornado_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_wt_wind_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_music_album_data.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/applications/applications_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/boot/boot_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/contacts/contacts_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/home/home_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/music/music_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/navigation/navigation_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/notifications/notifications_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/phone/phone_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/sc_timer/sc_timer_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/selector/selector_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/settings/settings_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/stopwatch/stopwatch_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/weather/weather_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/widgets/widgets_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/simulator/simulator_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_arcoiris/wd_arcoiris_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_arcoiris/wd_arcoiris_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_arcoiris/wd_arcoiris.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_dropdown/wd_dropdown_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_dropdown/wd_dropdown_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_dropdown/wd_dropdown.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_image/wd_image_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_image/wd_image_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_image/wd_image.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_label/wd_label_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_label/wd_label_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_label/wd_label.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_list/wd_list_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_list/wd_list_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_list/wd_list.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_obj/wd_obj_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_obj/wd_obj_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_obj/wd_obj.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_panel/wd_panel_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_panel/wd_panel_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_panel/wd_panel.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_segment/wd_segment_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_segment/wd_segment_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_segment/wd_segment.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wf_analog/wf_analog_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wf_analog/wf_analog_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wf_analog/wf_analog.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wf_item/wf_item_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wf_item/wf_item_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wf_item/wf_item.c)