list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/apps/app_item/app_item_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/control/control_bar/control_bar_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/control/control_button/control_button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/control/control_group/control_group_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/control/control_music/control_music_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/control/control_panel/control_panel_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/control/control_slider/control_slider_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/control/control_switch/control_switch_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_bar/hs_bar_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_button/hs_button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_card/hs_card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_column/hs_column_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_dropdown/hs_dropdown_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_info/hs_info_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_line/hs_line_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_row/hs_row_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_slider/hs_slider_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_space/hs_space_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_switch/hs_switch_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_text_large/hs_text_large_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_text_medium/hs_text_medium_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_text_normal/hs_text_normal_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/generic/hs_text_small/hs_text_small_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/notifications/notification_item/notification_item_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/settings/settings_about/settings_about_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/settings/settings_alert/settings_alert_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/settings/settings_battery/settings_battery_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/settings/settings_display/settings_display_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/settings/settings_item/settings_item_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/settings/settings_storage/settings_storage_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/settings/settings_system/settings_system_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/watchfaces/watchface_default/watchface_default_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/weather/daily_forecast/daily_forecast_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/weather/hourly_forecast/hourly_forecast_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/weather/weather_widget/weather_widget_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_14_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_16_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_18_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_20_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_30_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_40_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_70_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_100_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_140_data.c
  ${CMAKE_CURRENT_LIST_DIR}/helios_ui_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/helios_ui.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_application_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_back_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_brightness_empty_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_brightness_full_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_chat_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_connect_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_contacts_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_dnd_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_empty_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_folder_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_gear_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_list_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_measurement_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_music_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_mute_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_navigation_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_next_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_play_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_qr_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_running_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_settings_bell_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_settings_brightness_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_settings_harddisk_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_settings_information_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_settings_monitor_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_settings_power_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_settings_rotate_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_settings_smartwatch_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_sleep_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_stopwatch_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_timer_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_vibration_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_volume_high_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_volume_low_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_weather_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_wifi_data.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/applications/applications_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/boot/boot_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/home/home_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/notifications/notifications_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/settings/settings_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/weather/weather_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/core/widgets/widgets_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/simulator/simulator_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_arcoiris/wd_arcoiris_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_arcoiris/wd_arcoiris_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_arcoiris/wd_arcoiris.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_image/wd_image_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_image/wd_image_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_image/wd_image.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_list/wd_list_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_list/wd_list_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_list/wd_list.c)